# Generated by Django 4.0.2 on 2022-07-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comment_listing_comment_replies_to_listing_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='listing',
            field=models.ManyToManyField(blank=True, to='auctions.Listing'),
        ),
    ]
