# Generated by Django 4.0.2 on 2022-04-17 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
        migrations.AlterField(
            model_name='listing',
            name='min_bid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='auctions.bid'),
        ),
    ]
