# Generated by Django 4.0.2 on 2022-04-17 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bid_listing_alter_listing_min_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='min_bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='cur_bid',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.PROTECT, to='auctions.bid'),
            preserve_default=False,
        ),
    ]
