# Generated by Django 4.0.2 on 2022-04-24 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_bid_listing_remove_listing_min_bid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='cur_bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auctions.listing'),
            preserve_default=False,
        ),
    ]
